[package]
name = "mullvad-proc-macro"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version= "2", features = ["extra-traits"] }
quote = "1"